### ISSUE TITLE
react-native run-ios fails on haul-integrate.sh: No such file or directory

### ISSUE THREAD

**Issue by mattcubitt** [callstack-io/haul#110]
### Current Behavior

1. react-native init
2. yarn add --dev haul-cli
3. yarn run haul init
4. yarn run haul start -- --platform ios
5. react-native run-ios

Results in:
bash: ../node_modules/haul/src/utils/haul-integrate.sh: No such file or directory

** BUILD FAILED **
The following build commands failed:

        PhaseScriptExecution Integrate\ Haul\ with\ React\ Native build/Build/Intermediates/HaulBroken.build/Debug-iphonesimulator/HaulBroken.build/Script-AD0CE2C91E925489006FC317.sh
(1 failure)

### Expected Behavior

Init.js script is pointing to the wrong package. Changing line 283 to:

shellScript = "bash ../node_modules/haul-cli/src/utils/haul-integrate.sh";

Fixed the build and launches the app in the simulator. 

### Haul Configuration (webpack.haul.js)

module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});

### Environment

react-native-cli: 2.0.1
react-native: 0.43.2
haul-cli: 0.4.0
node: v7.7.3

**Comment by mattcubitt** [comment]
#111 Fixes this for me.

**Comment by grabbou** [comment]
Fixed in 0.4.1.

**Comment by 91ranjan** [comment]
If you are upgrading to 1.0.0-rc5 then this file has been removed.
Please look at the release 1.0.0-rc5 tag
https://github.com/callstack/haul/releases
and 
https://github.com/callstack/haul/blob/next/docs/Configuring_Your_Project.md
