### ISSUE TITLE
Source maps appear to be broken on 0.3.0

### ISSUE THREAD

**Issue by aem** [callstack-io/haul#112]
### Current Behavior

Opening the debugger only shows a bunch of `eval`d strings

### Expected Behavior

Opening the debugger should show sourcemapped files as 0.2.3 did

### Haul Configuration (webpack.haul.js)

```js
module.exports = ({ platform }, { resolve }) => ({
  entry: `./index.${platform}.js`,
  resolve: Object.assign(resolve, {
    alias: Object.assign({
      Immutable: 'immutable'
    }, resolve.alias || {}, extAliases)
  })
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.3.0
| react-native     |  0.42.0
| node             | 7.8.0
| npm or yarn      | yarn 0.22.0

**Comment by satya164** [comment]
Can you post a screenshot of what you see? I tried master just now and getting sourcemaps:

![image](https://cloud.githubusercontent.com/assets/1174278/24857412/d38f721e-1e05-11e7-92e3-7247b7b32b57.png)
