### ISSUE TITLE
Server breaks without dev tools open

### ISSUE THREAD

**Issue by aem** [callstack-io/haul#119]
I know I've filed a bunch of bugs, just want to let you all know that Haul is awesome and we love it here. Without Haul we would not have been able to use react-native with our internal infra so we're eternally grateful.

### Current Behavior
While dev tools are open, all works as expected. With dev tools closed, I see the following:

![image](https://cloud.githubusercontent.com/assets/1909883/24912993/a7207260-1ec7-11e7-9918-3b61d2212a45.png)

### Expected Behavior
Code should evaluate properly regardless of whether or not dev tools are open

### Haul Configuration (webpack.haul.js)

```js
module.exports = ({ platform }, { resolve }) => ({
  entry: `./index.${platform}.js`,
  resolve: Object.assign(resolve, {
    alias: Object.assign({
      Immutable: 'immutable'
    }, resolve.alias || {}, extAliases)
  })
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.5.0
| react-native     |  0.42.0
| node             | 7.8.0
| npm or yarn      | yarn 0.22.0

**Comment by satya164** [comment]
can you post the libraries you use? I suspect it's coming from a library. By default, we only transpile modules whose name start with `react`. for compatibility.

**Comment by aem** [comment]
the only libraries we're using are internal ones which i unfortunately can't post the code to, all protected stuff. i can say this was all working fine on 0.3.0 but is broken on 0.5.0

**Comment by satya164** [comment]
hmm... any of those libs are ES2015+?

don't think we changed something around transpiling, but need to check.

**Comment by aem** [comment]
Nah our internal stuff doesn't support anything past ES6 standard

**Comment by satya164** [comment]
@aem so it uses ES2015, JSC version on Android most likely doesn't support all of ES2015. We don't transpile everything under `node_modules` by default, but you can whitelist your own modules in `webpack.haul.js` to have your internal modules transpiled.

**Comment by aem** [comment]
But why would this only be an issue without the dev tools open?

**Comment by satya164** [comment]
@aem when devtools is open, your code runs in a web worker inside Google Chrome, which supports a different set of features. Chrome supports full ES2015, so you won't see any errors.
