### ISSUE TITLE
Public Communication Channel

### ISSUE THREAD

**Issue by jaridmargolin** [callstack-io/haul#121]
In an older issue, I saw reference to some sort of communication for Haul occurring on Slack. Is this a public Slack channel for outreach, or is this solely for internal team communication?

It would great to have a place to reach out; Gitter, Slack, IRC, etc...

**Comment by grabbou** [comment]
We have our Callstack.io own Slack (me and Satya work there). 

Curious what medium would make most sense here.

**Comment by jaridmargolin** [comment]
If you are already actively using slack, it may be most productive for you to utilize a slack channel. This is not uncommon. Babel for example utilizes slack: https://slack.babeljs.io/

I cannot comment on how easy the setup is, but it looks like behind the scenes they are utilizing https://github.com/rauchg/slackin.

May be helpful https://github.com/now-examples/slackin

**Comment by ferrannp** [comment]
We could just create a callstackoss public slack with channels like #haul and other oss projects we support.

**Comment by grabbou** [comment]
We now have `slack.callstack.io`, you can register and join `haul` channel. See you all there.

**Comment by satya164** [comment]
https://slack.callstack.io

**Comment by satya164** [comment]
@chelovekdrakon please check the discord link in README

**Comment by satya164** [comment]
https://discord.gg/zwR2Cdh
