### ISSUE TITLE
Stack traces fail to symbolicate

### ISSUE THREAD

**Issue by migueloller** [callstack-io/haul#122]
### Current Behavior

Stack traces fail to symbolicate correctly.

Here's the output from the Webpack server:
```
Error
    at readStream (~/HaulApp/node_modules/raw-body/index.js:211:17)
    at getRawBody (~/HaulApp/node_modules/raw-body/index.js:106:12)
    at read (~/HaulApp/node_modules/body-parser/lib/read.js:76:3)
    at textParser (~/HaulApp/node_modules/body-parser/lib/types/text.js:86:5)
    at Layer.handle [as handle_request] (~/HaulApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (~/HaulApp/node_modules/express/lib/router/index.js:317:13)
    at ~/HaulApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (~/HaulApp/node_modules/express/lib/router/index.js:335:12)
    at next (~/HaulApp/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.req.on (~/HaulApp/node_modules/haul-cli/src/server/middleware/rawBodyMiddleware.js:16:5)
```

Here's what the symbolication error looks like when debugging remotely:

![image](https://cloud.githubusercontent.com/assets/5677929/25050675/cd00e9dc-2116-11e7-9e9c-2e6976613322.png)

### Expected Behavior

Stack traces should symbolicate correctly.

### Haul Configuration (webpack.haul.js)

```js
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.5.0
| react-native     |  0.43.3
| node             | 7.8.0
| npm or yarn      | yarn@0.22.0

### Steps to Reproduce
```bash
react-native init HaulApp
cd HaulApp
yarn add --dev haul-cli
yarn haul init  # pick defaults
```

Modify `index.ios.js`:
```diff
 export default class HaulApp extends Component {
   render() {
+    throw new Error('Boom!')
     return (
       <View style={styles.container}>
         <Text style={styles.welcome}>
```
```bash
yarn haul start -- --platform ios
react-native run-ios
```

### Proposed Solution
I'm happy to send PR with a fix if anybody can point me in the right direction.

🍺

**Comment by skellock** [comment]
This is failing because [these two middleware](https://github.com/callstack-io/haul/blob/master/src/server/index.js#L60-L61) aren't compatible.

`rawBodyMiddleware` brings `req.rawBody` to the table now.  That gives `symbolicateMiddleware` all the info it needs to run.  We should [switch over](https://github.com/callstack-io/haul/blob/master/src/server/middleware/symbolicateMiddleware.js#L81,L86) to using that instead of `body`.

This will allow us to [drop a dependency](https://github.com/callstack-io/haul/blob/master/package.json#L32) too. 🎉 

I can find time tomorrow to knock this out, but I'd be grateful if you wanted to call dibs on this.

Thanks for the great repro steps.

**Comment by migueloller** [comment]
@skellock, thanks for the info and quick reply! I'll send a PR. 😁

**Comment by migueloller** [comment]
Ok, @skellock, I'm going to need some pointers here. I got rid of the two incompatible middleware but now there's a new error. Basically, [`consumer.originalPositionFor`](https://github.com/migueloller/haul.git) is returning a `lookup` that has [`source`](https://github.com/callstack-io/haul/blob/master/src/server/middleware/symbolicateMiddleware.js#L125) equal to `null`.

The following error is that `replace` can't be called on null.

Does a `ReactNativeStackFrame` always expect `file` to be a string?

**Comment by migueloller** [comment]
Ok, just found the issue. I'm using [React Native Debugger](https://github.com/jhen0409/react-native-debugger) and Haul can't handle the last stack frame which has the following filename: `file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js`

Usually, it would be `http://localhost:8081/debuggerWorker.js`. I'll send the PR doing the fix for the middleware. Any thoughts on how to handle React Native Debugger?
