### ISSUE TITLE
Open File in Editor Support

### ISSUE THREAD

**Issue by skellock** [callstack-io/haul#123]
In the React Native simulator, you can tap a stack frame and your editor will open to that file.

[To do this](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/openFileInEditor.js#L17), they POST to '/open-stack-frame' passing along `{file, lineNumber}`.

What happens next is [kinda involved](https://github.com/facebook/react-native/blob/master/local-cli/server/util/launchEditor.js).

Supporting every single editor doesn't mentally scale, but maybe just offering a callback/plugin to haul where one could define their editor?

Would you guys be open to a PR supporting a dumbed down version of this to start?

**Comment by satya164** [comment]
Yeah, a PR will be great! Thank you.

**Comment by ds300** [comment]
Would you be open to a PR which just copy+pastes FB's code, retaining their BSD license in the header? I think adding a customisable solution would be nice eventually though.

**Comment by grabbou** [comment]
I'd prefer to have an in-house solution for that particular problem.

**Comment by skellock** [comment]
Ya my plan was to start with `ENV` but with a format string of sorts... each editor has slightly different ways to open with arguments... with a colon, with a space, with arguments.... and then there's VSCode :/.

I won't have time this week unfortunately, but I have a quiet weekend coming up.  🎉

**Comment by skellock** [comment]
"plan b was to ask if you'd guys would be interested in a plugin system to extend the express middleware".  - Captain ScopeCreep

**Comment by satya164** [comment]
@skellock yes, I was thinking about a similar thing, expose parts of haul as a set of express middlewares, which you can use in your own express server and add additional middlewares/wrap existing ones as you need.

**Comment by satya164** [comment]
Though we'd want to support most popular editors by default.

**Comment by skellock** [comment]
Well,

* doesn't work at all `<--- we are here`
* use `opn` (already a dep) and rely on the system?
* read `$EDITOR`/`$VISUAL`/etc
* provide a customizable `ENV`
* provide a customizable `ENV` with a format string
* auto-detect the shit out of it `<--- we want to be here`

Do you want to just maybe start on 2 or 3 (+ express middleware) and maybe have something more awesome next week?

**Comment by satya164** [comment]
AFAIK React Native Packager reads `EDITOR` and `REACT_EDITOR`, so we should probably do that.

**Comment by skellock** [comment]
`https://www.npmjs.com/package/open-in-editor`  gonna leave this here.  I know nothing about it... looks promising.  as does everything when you don't install it.

Will tackle it this weekend.  If someone beats me to it, that's 100% ok with me!  :)
