### ISSUE TITLE
@providesModule and require images support

### ISSUE THREAD

**Issue by shahen94** [callstack-io/haul#128]
### Current Behavior

I've tried to move from default packager to this library, but haul gives me an errors.

```
ERROR in ./src/navigator/Navigator.js
Module not found: Error: Can't resolve 'AppColors' in '/Users/simply/Projects/justhive/jh-mobile/src/navigator'
 @ ./src/navigator/Navigator.js 137:154-174
 @ ./src/navigator/index.js
 @ ./index.ios.js
 @ multi ./~/haul-cli/src/utils/polyfillEnvironment.js ./index.ios.js
```

or this one
```
ERROR in ./src/navigator/Navigator.js
Module not found: Error: Can't resolve 'img/icons/icon_nav_feed.png' in '/Users/simply/Projects/justhive/jh-mobile/src/navigator'
 @ ./src/navigator/Navigator.js 137:779-817
 @ ./src/navigator/index.js
 @ ./index.ios.js
 @ multi ./~/haul-cli/src/utils/polyfillEnvironment.js ./index.ios.js
```

### Expected Behavior
Import or require files as it's doing react packager

### Haul Configuration (webpack.haul.js)

```
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.5.0
| react-native     |  0.41
| node             | 7.5.1
| npm or yarn      | yarn 0.15.1

**Comment by satya164** [comment]
Haul doesn't support `@providesModule` by default. It is used internally at FB and suits their large codebase, but not ideal for small OSS projects. Not supporting haste improves performance and avoids duplicate module errors.

It's just webpack, so you could try available plugins on NPM to support Haste, though I would suggest to refactor your code not to use haste. You can use https://github.com/tleunen/babel-plugin-module-resolver which is a nicer alternative if you want to save typing.

Regarding images, can you please post some sample code? Haul supports requiring assets. But it doesn't support requiring images via the old `image!` syntax since it's deprecated now.

**Comment by shahen94** [comment]
Thanks for so quick response !

![screen shot 2017-04-19 at 4 27 14 pm](https://cloud.githubusercontent.com/assets/13334788/25180002/49546824-251d-11e7-8caa-c5aba8bebf70.png)

This is my folder structure. i'm able to require image from img folder from everywhere in project.

**Comment by satya164** [comment]
This is part of the Haste module system and only supported by the React Native packager. You will need to use `https://github.com/tleunen/babel-plugin-module-resolver` to achieve this behaviour with Haul. You won't need to have a `package.json` anymore.

**Comment by shahen94** [comment]
I've configured babel-plugin-module-resolver in my .babelrc file, but still getting the same error.
Should i add loader in webpack config ?

**Comment by satya164** [comment]
Can you post the whole `.babelrc`? You shouldn't need to configure anything for webpack.

Also just to be safe, try deleting the `.happypack` folder

**Comment by shahen94** [comment]
Now comes other error
![screen shot 2017-04-20 at 4 04 25 pm](https://cloud.githubusercontent.com/assets/13334788/25229892/2a5918a4-25e3-11e7-89c7-75c15c2803eb.png)

**Comment by shahen94** [comment]
```
const shaders = GL.Shaders.create({
  XproII: {
    frag: `
      precision highp float;
      varying vec2 uv;

      uniform sampler2D inputImageTexture;
      uniform sampler2D inputImageTexture2;
      uniform sampler2D inputImageTexture3; 

      void main () {

        vec3 texel = texture2D(inputImageTexture, uv).rgb;

        vec2 tc = (2.0 * uv) - 1.0;
        float d = dot(tc, tc);

        texel.r = texture2D(inputImageTexture3, vec2(d, (1.0-texel.r))).r;
        texel.g = texture2D(inputImageTexture3, vec2(d, (1.0-texel.g))).g;
        texel.b  = texture2D(inputImageTexture3, vec2(d, (1.0-texel.b))).b;

        texel.r = texture2D(inputImageTexture2, vec2(texel.r, .83333)).r;
        texel.g = texture2D(inputImageTexture2, vec2(texel.g, .5)).g;
        texel.b = texture2D(inputImageTexture2, vec2(texel.b, .16666)).b;

        gl_FragColor = vec4(texel, 1.0);
      }`
  }
});

```

**Comment by satya164** [comment]
Haul doesn't transpile modules under node_modules for performance and to avoid breaking third party libs. You can override the `exclude` property to transpile that module in the config you get as the argument

https://github.com/callstack-io/haul/blob/master/src/utils/makeReactNativeConfig.js#L81
https://github.com/callstack-io/haul#limitations

We'll have better docs on this soon
