### ISSUE TITLE
Flow error on new generated react-native project

### ISSUE THREAD

**Issue by ferrannp** [callstack-io/haul#142]
### Current Behavior
Flow error:

```
node_modules/haul-cli/src/server/middleware/systraceMiddleware.js:22
 22:   // $FlowFixMe: `req.rawBody` is added by rawBodyMiddleware
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```

### Expected Behavior
No flow errors due haul.

### Haul Configuration (webpack.haul.js)
Default one with `0.5.0`.

### Your Environment
Just create new react-native project with `react-native init TestProject` which has `.flowconfig` inside with version `0.40.0` and then install and init haul.

| software         | version
| ---------------- | -------
| Haul             |  0.5.0
| react-native     |  0.43.4
| node             |  6.3.1
| npm or yarn      | 3.10.3 & 0.22.0

**Comment by grabbou** [comment]
Supported version by `haul` is 0.42.0 as in `flowconfig`. I guess that's the reason error occurs.
