### ISSUE TITLE
Cannot build RN 0.44

### ISSUE THREAD

**Issue by neverlan** [callstack-io/haul#144]
### Current Behavior
![image](https://cloud.githubusercontent.com/assets/5860671/25584864/079cf318-2e98-11e7-91e5-1c8fe39428dd.png)

### Expected Behavior
Should build.

### Haul Configuration (webpack.haul.js)
Tested with default config.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  master
| react-native     |  0.44.0
| node             | 7.4.0
| npm or yarn      | npm 4.3.0

**Comment by llaine** [comment]
Experiencing the same issue.

**Comment by satya164** [comment]
That actually looks like invalid syntax to me :(

**Comment by GeeWee** [comment]
It seems this broke between 0.43 and 0.44 #150 
I checked the RN change logs and it's not a new file, and this exact line was there in 0.43 as well.
For some reason the flow-types don't get stripped. Maybe @grabbou has a better idea of what's going on, he seems to know a thing or two about new RN releases.

**Comment by yamafaktory** [comment]
I was facing a similar issue after switching to React Native **v0.44.**. Running `react-native-git-upgrade` fixed it automagically 🌟 (https://github.com/facebook/react-native/tree/master/react-native-git-upgrade).

**Comment by grabbou** [comment]
I just created a sample app with `react-native init` , run `init` and then, built successfully. My reasoning is that installing dependencies once again updated some intermediate packages that are now, able to properly recognise the flow format mentioned in first post.

Please let me know if you still occur any issues on `master` or `latest` after installing new version.
