### ISSUE TITLE
Can't remote debug: global.self throws error

### ISSUE THREAD

**Issue by jspears** [callstack-io/haul#146]
### Current Behavior
When running in remote debugger using the IOS simulator the browser chokes on 
haul-cli/src/utils/polyfillEnvironment.js
```js
global.self = global
```
Commenting out this line fixes it, and seems to work in simulator

The error looks like this.
```
TypeError: Cannot assign to read only property 'self' of object '#<DedicatedWorkerGlobalScope>'
    at Object.<anonymous> (polyfillEnvironment.js:32)
```
Also wrapping in a try/catch seems to work also.

### Expected Behavior
Expect remote debugging to work.

### Haul Configuration (webpack.haul.js)
default haul configuration

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |     "^0.5.0",
| react-native     |     "0.44.0",
| node             | 6.10.2
| npm or yarn      | yarn
| chrome |  57.0.2987.133

**Comment by jspears** [comment]
Also checking if global.self exists before assigning seems to work, which is probably the safest thing to do.  Guessing this a change in chrome version issue.

**Comment by skellock** [comment]
Ya this was a [totally hacky](https://github.com/callstack-io/haul/blob/master/src/utils/polyfillEnvironment.js#L31) way to get React Native to behave. Without this in place, it was causing `fetch` due to some really strange timing issue.

I haven't re-evaluated this in 0.44.x, but it was failing in 0.43.x and 0.42.x.

Does symbolication work for you if you handle that line safely?

**Comment by jspears** [comment]
Ahh "symbolication" not sure what you mean,and once I do I am gonna use that word like 3 times today.

**Comment by skellock** [comment]
It's a sweet word!

So you know with React Native's redbox screen of death that shows when an error happens?  Well, RN goes back to the packager to resolve the source map to the "real" line of code.  They call that symbolication (I guess).

So, if you force an error to happen:

`render () { boom() }`

You'll see a stack trace.  Then a moment later (hopefully), the filename will turn into something you recognize.

**Comment by grabbou** [comment]
This has been fixed in https://github.com/callstack-io/haul/commit/ae73662fce4c5e41ac78d0d5ee5d6a16fb8b1c2b and will be released shortly.
