### ISSUE TITLE
Supporting gradle assembleRelease task

### ISSUE THREAD

**Issue by kernelgonnapanic** [callstack-io/haul#151]
### Current Behavior
Currently when running assembleRelease task from react-native to bundle apk, gradle is using underneath gradle react.gradle config from `react-native`. In this config classic `react-packager` is used to bundle js files.

### Expected Behavior
I would like to use `haul` to bundle js files when running assembleRelase from react native.

Is there a recommended way to switch to using haul here?

**Comment by grabbou** [comment]
CC: @satya164 I think you were working on supporting this during `init` phase.

**Comment by satya164** [comment]
Init doesn't do this right now, but it's already in README

**Comment by grabbou** [comment]
Going to close this one then, the ultimate solution is to upgrade to latest `react-native` and follow `readme` setup.
