### ISSUE TITLE
SyntaxError on iOS 9.x with React Native 44

### ISSUE THREAD

**Issue by grabbou** [callstack-io/haul#159]
We have this issue before, I need to investigate why on certain iOS versions it happens. It has something to do with Safari version and the subset of spec supported.

No issues on iOS 10.x

**Comment by skellock** [comment]
Is it Symbols by any chance?  I know on older version (< iOS 8.2 and Android 4.x), we need to polyfill them.

**Comment by grabbou** [comment]
Hm, could be! But we got stuff here: https://github.com/callstack-io/haul/blob/master/src/utils/polyfillEnvironment.js#L11-L19, right?

**Comment by skellock** [comment]
Do you have an example of the error?

If it's a missing `Symbol` thing, it should be easy to track down.  I've used [this polyfiller](https://github.com/medikoo/es6-symbol) (usage in entry point is `import 'es6-symbol/implement'`) which helps when 3rd party libs use `Symbol`s.  There's probably a dependency-free version of it somewhere too.

The other thing that has bitten me on older iOS devices due to strange errors is importing 3rd party libs who have their .xcodeproj targets set to higher versions of iOS.

Not [naming](https://github.com/airbnb/react-native-maps/blob/master/lib/ios/AirMaps.xcodeproj/project.pbxproj#L263) names though.

**Comment by grabbou** [comment]
Not sure. Even deleting entire `index.ios.js` (emptying it) triggers the
error, so I guess it's coming from React / React Native source file.

Will check tomorrow when testing on older devices.

If you get a chance to spin iOS 9.x in the meantime, I'd appreciate any
help! Thanks for discussing that :D

**Comment by skellock** [comment]
Ya, seems like it's happening a bit earlier in the chain then that.

The exact error firing on this sample project here is:  

`Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

Tested and failing on:
* haul 0.6
* rn 0.44.2
* simulator: iPhone 5s @ iOS 8.2, 8.4 & 9.2

Maybe some part of babel compiling process might not be working?  It looks like everything is in place.  Looks like you're using the right preset (`react-native`).

Best part of all this: If you "Debug JS Remotely", it works.  🤣

**Comment by rauliyohmc** [comment]
Happening in Android simulator as well (tested with Genymotion device, Google Nexus 5)

![image](https://cloud.githubusercontent.com/assets/4982414/26830861/94152998-4aca-11e7-8318-4c27247c2d33.png)

Being the curlprit, `printString` module from react-native, which is apparently the only one that keeps `const` declarations after transpilation:

![image](https://cloud.githubusercontent.com/assets/4982414/26831017/263f7684-4acb-11e7-8d6d-d8b39e189d20.png)

**Comment by rauliyohmc** [comment]
I dug a bit more and that module/repository [was moved into jest](https://github.com/thejameskyle/pretty-format) some time ago, so it doesn't even make sense to be bundled with either packager or haul. Packager, though, transpiles it properly. Guessing a temporary solution for Haul would be to explicitly transpile that library within `webpack.haul.js` config using `babel` loader and `include` option.

**Comment by grabbou** [comment]
Today is a good day! Thanks @rauliyohmc and @skellock for fixing the most annoying issue of all time! The culprit was `pretty-format`. Whitelisted it.

**Comment by Unforgiven-wanda** [comment]
@grabbou Can you please elaborate? Excluding  `pretty-format` didn't solve this for me

**Comment by grabbou** [comment]
This has been fixed few versions ago - are you running latest haul?

**Comment by Unforgiven-wanda** [comment]
I kinda gave up on it since. But will try it again on my next project :)

**Comment by grabbou** [comment]
Okies, happy to help in that case. Feel free to sign up on
slack.callstack.com for better "real-time" support ;)
