### ISSUE TITLE
Larger assets are not correctly scaled

### ISSUE THREAD

**Issue by grabbou** [callstack-io/haul#166]
In my project, I only have `logo@3x.png`. Packager scales it down nicely, I guess on iPhone it will device read dimensions by `3`.

However, Haul loads it raw resulting in the image taking too much space.

Screenshot:
<img width="476" alt="screen shot 2017-06-08 at 11 07 19" src="https://user-images.githubusercontent.com/2464966/26920912-c52052a8-4c3a-11e7-930d-c8a201acfd9f.png">

CC: @satya164

**Comment by grabbou** [comment]
Any update on this? Need to release a new version soon 💯

**Comment by satya164** [comment]
@grabbou oh sorry, I'll send the pr soon. just some testing needed

**Comment by grabbou** [comment]
No worries, juts wanted to follow up on status.

**Comment by grabbou** [comment]
Is this fixed now?
