### ISSUE TITLE
Reference to a file within an installed module causes error

### ISSUE THREAD

**Issue by jonnywyatt** [callstack-io/haul#169]
### Current Behavior
A reference to a file within an installed NPM module generates a red box error on the device.

```
ReferenceError: Can't find variable: ScreenLayoutWrapper (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13366

./node_modules/module-ui-components/react-native/components/ScreenLayoutWrapper.js@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13366:21
```
The contents of the file generating the error is:
```
import React from 'react';
import PropTypes from 'prop-types';
import {
	View
} from 'react-native'
import Header from './Header/Header';
import {globalStyles as styles} from '../styles'

export default ScreenLayoutWrapper = (WrappedComponent, options) => {
	return class extends React.Component {
		static navigationOptions = {header: null};
		render() {
			return (
        <View style={styles.screenContainer}>
            <Header appId={options.appId} title={options.title} />
            <WrappedComponent {...this.props} />
        </View>
			)
		}
	}
}
```

This file is part of an installed NPM module and is pulled into the main app with:

```
import ScreenLayoutWrapper from 'module-ui-components/react-native/components/ScreenLayoutWrapper';
```

The reason I'm asking if this is a Haul / Webpack error is, it doesn't occur if I use the standard RN packager.

### Expected Behavior
import / file should execute without error.

### Haul Configuration (webpack.haul.js)
```
module.exports = ({platform}, defaults) => ({
  entry: `./index.${platform}.js`,
  module: {
    ...defaults.module,
    rules: [
      ...defaults.module.rules,
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(module-ui-components)\/).*/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015', 'react', 'stage-1']
          }
        }
      }
    ]
  }
});
```
### Your Environment
Android 7.0 running on real device (Samsung S7)

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.0
| react-native     |  0.45.1
| node             | 7.9
| npm or yarn      | yarn 0.24.6

**Comment by skellock** [comment]
You certain that shouldn’t be `export default const` instead?

**Comment by satya164** [comment]
That's wrong syntax unless I'm missing something. You need to either `export default` without the variable assignment, or define it as `const ScreenLayoutWrapper` and then do `export default ScreenLayoutWrapper` at the bottom.

The fact that RN packager works seems like a bug, unless this is actually a valid syntax.

**Comment by jonnywyatt** [comment]
That worked! Thanks to you both.
