### ISSUE TITLE
Release build fails with react-native@0.44.0

### ISSUE THREAD

**Issue by JulioC** [callstack-io/haul#179]
### Current Behavior

I have a project using resole.alias property from Webpack.  When building it for release on android with `cd android && ./gradlew assembleRelease`, it throws an error: 

:app:bundleReleaseJsAndAssets
> Unable to resolve module `app/screens/Splash` from `C:\workspace\my-project\src\navigation\Navigator.js`: Module does not exist in the module map or in these directories:
>   C:\workspace\my-project\node_modules\app\screens
> [...]
> :app:bundleReleaseJsAndAssets FAILED

### Expected Behavior

It should work, as it does with `haul start`. 

Since it works with react-native@0.45.0, I'd suggest updating the note on the README, recommending at least that version.

### Haul Configuration (webpack.haul.js)

```js
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');

module.exports = ({ platform, root }, defaults) => merge(defaults, {
  entry: `./index.${platform}.js`,
  resolve: {
    alias: {
      app: path.join(root, 'src'),
    },
  },
});

```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.2
| react-native     |  0.44.0
| node             | v6.10.0
| npm or yarn      | 0.20.3

**Comment by grabbou** [comment]
I think the issue is that you are not using Haul to bundle in release, but Packager (we added version to overwrite it in 0.45). Since you are using `alias`, `packager` is not recognising it.

@satya164 what would be the most efficient way to use Haul prior to 0.45?

**Comment by satya164** [comment]
@grabbou we added that is `0.43` -> https://github.com/callstack-io/haul#getting-started. On older versions we need to edit the `node_modules/react-native/react.gradle` file

@JulioC can you share the `android/app/build.gradle` file?

**Comment by JulioC** [comment]
Here it is. I've removed some content I believe it's not related to this issue.

```gradle
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile

project.ext.react = [
    cliPath: "node_modules/haul/bin/cli.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"

    /* other stuff... */
}

/* other stuff... */

```
