### ISSUE TITLE
Add donations!

### ISSUE THREAD

**Issue by ericwooley** [callstack-io/haul#184]
Haul has saved my bacon several times over. 

You should consider adding a donate button to the readme.

**Comment by grabbou** [comment]
I am soo happy that Haul has saved you some time and made it easier to do things! We work on Haul internally, at Callstack, as a part of our open source program. However, I recommend you to donate to Webpack, which is an underlaying bundler and most important building block of Haul. It is being crafted and maintained by open source collaborators and is seeking donations.
https://opencollective.com/webpack
