### ISSUE TITLE
Cannot find module happypack

### ISSUE THREAD

**Issue by ericwooley** [callstack-io/haul#189]
### Current Behavior
After install, with npm, sometimes 'happypack' cannot be found.

I am also using lerna, to add confusion

### Expected Behavior
happypack should be found.

### Haul Configuration (webpack.haul.js)
standard happy pack config

### Your Environment
lerna
osx
npm 5.0.3

| software         | version
| ---------------- | -------
| Haul             |  beta-2
| react-native     |  0.45
| node             | 8.1.3
| npm or yarn      | both

_______________________

I think the problem may have something to do with git, but i'm not sure.

I'm curios why the dependency is a specific git commit instead of a standard npm module.

**Comment by ericwooley** [comment]
Accedentally submitted twice.

**Comment by zamotany** [comment]
I had few problems with `lerna` and `npm@5` together, so maybe try to install the latest `npm@5.3.0` and see if that helps. It's also possible that `npm@5` can handle github paths - `github:amireh/happypack#3256a3380dde2e06e3ad2ca3b41e9a81fd4f9673`.

**Comment by lalit-atrish** [comment]
did you find any solution?

**Comment by zamotany** [comment]
@lalit-atrish We stopped using `happypack` a long time ago, please if you can use latest version or even better our soon-to-be-official revamped version on [`next`](https://github.com/callstack/haul/tree/next) branch.
