### ISSUE TITLE
happypack module not found (sometimes)

### ISSUE THREAD

**Issue by ericwooley** [callstack-io/haul#190]
### Current Behavior
After install, with npm, sometimes 'happypack' cannot be found.

I am also using lerna, to add confusion

### Expected Behavior
happypack should be found.

### Haul Configuration (webpack.haul.js)
standard haul config

### Your Environment
lerna
osx
npm 5.0.3

| software         | version
| ---------------- | -------
| Haul             |  beta-2
| react-native     |  0.45
| node             | 8.1.3
| npm or yarn      | both

_______________________

I think the problem may have something to do with git, but i'm not sure.

I'm curios why the dependency is a specific git commit instead of a standard npm module.

**Comment by zamotany** [comment]
I had few problems with `lerna` and` npm@`5 together, so maybe try to install the latest `npm@5.3.0` and see if that helps. It's also possible that `npm@5` or `lerna` can handle github paths - `github:amireh/happypack#3256a3380dde2e06e3ad2ca3b41e9a81fd4f9673`.

**Comment by ericwooley** [comment]
I tried with both npm and yarn, npm 5.0.3 and yarn 0.27. I'll try with npm 5.3.0 as well.

Would there be a reason I shouldn't specify a version of happypack that is published?

**Comment by zamotany** [comment]
I don't really know. It's possible that `3.1.0` would work, but I believe @grabbou has the answer to that question.

**Comment by ericwooley** [comment]
adding happypack@3.1.0 to my package.json dependency specification seems to have fixed the issue.

**Comment by grabbou** [comment]
Interesting why `happypack` would have to be present in your project dependencies. Be sure to reinstall node_modules. Sometimes bad things can happen over time.

**Comment by ericwooley** [comment]
We went through the ringer of trying to get it working. Node versions, npm versions, installing manually, switching to yarn, deleting the node_modules between every step. 

I think it happened when the npm install failed initially through lerna, and something is cached from the git module somewhere. After a while it just started working on one machine (cache expired?) and switching to the published npm module worked on the other.
