### ISSUE TITLE
Assets urls are not resolved correctly

### ISSUE THREAD

**Issue by zamotany** [callstack-io/haul#199]
The assets URLs are invalid. Probably it's the asset loader fault.

### Current Behavior
When using images the app makes request with an invalid url:
```
GET /http://localhost:8081//assets/ios/media/calendar.png 404 191 - 0.627 ms
GET /http://localhost:8081//assets/ios/media/calendar.png 404 191 - 4.024 ms
GET /http://localhost:8081//assets/ios/media/location.png 404 191 - 0.653 ms
GET /http://localhost:8081//assets/ios/media/location.png 404 191 - 0.917 ms
GET /http://localhost:8081//assets/ios/media/information.png 404 194 - 0.681 ms
GET /http://localhost:8081//assets/ios/media/information.png 404 194 - 0.766 ms
```

### Expected Behavior
The assets should be requested with a valid url, eg `http://localhost:8081/assets/ios/media/calendar.png`

### Haul Configuration (webpack.haul.js)
Default

### Your Environment
| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.1
| react-native     |  0.46.4
| node             | 7.10.0
| npm      | 4.6.1

**Comment by satya164** [comment]
Can repro this. Probably broke with https://github.com/callstack-io/haul/commit/77e82e2d69cacc837cea1431752cc0ffa7678c62 ?

**Comment by zamotany** [comment]
It's related to HMR.
