### ISSUE TITLE
Silent failure on build errors

### ISSUE THREAD

**Issue by joearasin** [callstack-io/haul#204]
This is a bit of a weird one -- but on some packaging errors (i.e. if I am exporting a generator, for example, which chokes React Native's build), the error gets silently swallowed, with haul outputting "Built successfully!", but opening the IOS simulator reveals "Module AppRegistry is not a registered callable module (calling runApplication)".

To reproduce, drop something along the lines of:
```javascript
export function* kaboom() {
  console.log("Boom");
} 
```
into a file that is getting packaged by haul. 

My shell ends up outputting something along the lines of: 
```
GET /index.ios.bundle 200 3936836 - 14.583 ms
GET /index.ios.bundle 304 undefined - 5.852 ms
```
That 304 does not show up when things run smoothly.

### Haul Configuration (webpack.haul.js)

```javascript
const fs = require("fs");

module.exports = ({ platform }, defaults) => ({
  entry: `./index.${platform}.js`,
  resolve: {
    ...defaults.resolve,
    modules: [
      fs.realpathSync("node_modules"),
      fs.realpathSync("../common/node_modules"),
    ],
  },
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.2
| react-native     |  0.44.0
| node             |  8.1.4
| npm or yarn      |  yarn 0.27.5

**Comment by Krizzu** [comment]
Hey @joearasin, thanks for filling this issue.

I've created a PR #205 to fix this problem.


All best.

**Comment by joearasin** [comment]
Awesome. thanks for the quick fix. I think the changes in today's release (maybe #183) actually fixed my issue, but anything helps!

**Comment by Krizzu** [comment]
@joearasin 

Glad you have your problem solved.

Cheers :)
