### ISSUE TITLE
yarn package not updated

### ISSUE THREAD

**Issue by ericyip** [callstack-io/haul#206]
### Current Behavior

```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Integrate\ Haul\ with\ React\ Native build/Build/Intermediates/petter.build/Debug-iphonesimulator/petter.build/Script-AD0CE2C91E925489006FC317.sh
(1 failure)
```
### Expected Behavior

Using the lastest verison of haul. I need to copy& paste the `haul-integrate.sh` from github everytime to solve it

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.2
| react-native     |  0.46.4
| node             | v6.9.1
| yarn      | v0.24.5

**Comment by zamotany** [comment]
@grabbou I think we need a new release with this fix https://github.com/callstack-io/haul/commit/870753d1df5f2d6f878584adb95a370bc2b5b169

**Comment by grabbou** [comment]
Going to do it now.
