### ISSUE TITLE
Can't debug with Chrome

### ISSUE THREAD

**Issue by rtomchinsky** [callstack-io/haul#210]
### Current Behavior
When debugging with Chrome, the debugger does not show the scripts from webpack in the sources tab.

![current](https://user-images.githubusercontent.com/2497755/28940124-0221078c-786a-11e7-853f-fb83adb7f434.PNG)

### Expected Behavior
Source files are shown in the sources tab and it is possible to place breakpoints and debug the code, i.e.:

![expected](https://user-images.githubusercontent.com/2497755/28940141-10307632-786a-11e7-8db1-9b9ec12da745.PNG)

### Haul Configuration (webpack.haul.js)
```javascript
var webpack = require('webpack');

module.exports = ({ platform }, { module, resolve, plugins }) => ({
  entry: `./src/index.${platform}.tsx`,
  module: {
    ...module,
    rules: [
      {
        test: /\.tsx?$/,
        use: [
          'babel-loader',
          'ts-loader'
        ]
      },
      ...module.rules
    ]
  },
  resolve: {
    ...resolve,
    extensions: [
      '.ts',
      '.tsx',
      `.${platform}.ts`,
      '.native.ts',
      `.${platform}.tsx`,
      '.native.tsx',
      ...resolve.extensions
    ]
  },
  plugins: [
    ...plugins,
    new webpack.optimize.ModuleConcatenationPlugin()
  ]
});
```

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.4
| react-native     |  0.47.1
| node             | 7.9.0
| npm or yarn      | 5.3.0

### Other Information
While attempting to resolve this issue, I found that the file [debuggerWorker.js](https://github.com/callstack-io/haul/blob/master/src/server/assets/debuggerWorker.js) is loading the app file using `fetch`, replacing `'this["webpackHotUpdate"]'` with `'self["webpackHotUpdate"]'` and then `eval`ing it.

While this works (as in, the app works), I believe Chrome doesn't understand that the files loaded through `fetch` should be added as source files.

I tried replacing the line

```javascript
fetch(message.url).then(resp => resp.text()).then(evalJS);
```
with

```javascript
try {
  importScripts(message.url);
} catch (e) {
  self.ErrorUtils.reportFatalError(e);
} finally {
  self.postMessage({ replyID: message.id });
  processEnqueuedMessages();
}
```

but this just left a blank screen. I had to use the following for it to actually work:

```javascript
var error;
try {
  importScripts(message.url);
} catch (e) {
  error = e;
}
processEnqueuedMessages();
sendReply(null, error);
```

**Comment by satya164** [comment]
cc @Krizzu

**Comment by zamotany** [comment]
We can't use `importScripts` because the stack trace for errors is useless. Replacement of `'this["webpackHotUpdate"]'` with `'self["webpackHotUpdate"]'` is just for the webpack boostraping logic so that it doesn't throw the error.

**Comment by zamotany** [comment]
Try adding `devtool: 'eval-source-map',` to `webpack.haul.js`.

**Comment by rtomchinsky** [comment]
That works, thanks!

**Comment by Fconstant** [comment]
> Try adding devtool: 'eval-source-map', to webpack.haul.js.

Shouldn't this be at the docs?

**Comment by zamotany** [comment]
Probably this needs a PR to Haul.

**Comment by springHyc** [comment]
@zamotany 
> Try adding devtool: 'eval-source-map', to webpack.haul.js.
添加这个之后，文件是不换行的，如何设置为换行的呢？
