### ISSUE TITLE
Hot loading isn't working because it cannot connect to the development server ? 

### ISSUE THREAD

**Issue by cuduy197** [callstack-io/haul#219]
I have issue : Hot loading isn't working because it cannot connect to the development server ?
When i disable hot loading, it work normal? , How do i enable hot loading ❓

**Comment by cuduy197** [comment]
And sometime app didn't reload when i enable live reload ?

**Comment by drakmail** [comment]
See README.md:

> 
> The following features are unlikely to be supported in the future:
> 
> Developer menu -> Enable Hot Reloading: use webpack.haul.js config instead

**Comment by zamotany** [comment]
#182

**Comment by grabbou** [comment]
Closing as this feature is in progress.

**Comment by riteekachhabra** [comment]
Is this feature still in progress?
