### ISSUE TITLE
React-native 0.48.1 content-type issue

### ISSUE THREAD

**Issue by joearasin** [callstack-io/haul#228]
I just upgraded what is effectively a Hello World react-native app + Haul to react-native 0.48.1, and now upon launching I am getting an error in my simulator:

> Expected Content-Type to be 'application/javascript' or 'text/javascript' but got 'application/octet-stream; charset=UTF-8'

My assumption is that https://github.com/facebook/react-native/blob/v0.48.1/React/Base/RCTJavaScriptLoader.mm#L247 is tripping on something in haul, as running `curl -v -D - http://localhost:8081/index.ios.bundle -o /dev/null` indicates that the content-type of my bundle is indeed `Content-Type: application/octet-stream; charset=UTF-8`.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.5 
| react-native     |  0.48.1
| node             | 8.4.0
| npm or yarn      | 0.27.5

**Comment by joearasin** [comment]
To clarify what is going on internally:
webpack-dev-middleware is using mime.lookup to determine the content-type to return for "index.ios.bundle". ".bundle" being an unknown type, it defaults to applications/octet-stream. The default bundle file needs to be "index.ios.bundle.js" or something to that effect.

**Comment by joearasin** [comment]
Anyway -- it seems like there are two possible solutions:
1) Convince the webpack-dev-middleware folks to expose the mimetype detector as a parameter, allowing for custom mimetype detection.
2) Set up haul such that, when running in server mode, it bundles to "index.ios.bundle.js" and rewrites the request from "index.ios.bundle" to "index.ios.bundle.js"

**Comment by joearasin** [comment]
Just attempted solution (2) above. It does not work, b/c webpack-dev-middleware automatically appends "charset=UTF-8" to the mime-type header, which causes react-native to choke. This could be overridden by using the "headers" option to webpack-dev-middleware, but I imagine images and such would then break.

**Comment by joearasin** [comment]
I just opened a PR on webpack-dev-middleware that is necessary for solution (1) -- I think that's ideal, as this implementation is more than a bit of a hack.

**Comment by qrush** [comment]
Hit this myself! Big +1 to fixing this. In the meantime I commented out the following lines to skip that check...

https://github.com/facebook/react-native/blob/master/React/Base/RCTJavaScriptLoader.mm#L287-L288

🙈

**Comment by Titozzz** [comment]
Hello, happens to me too, so I can't upgrade to 0.48 until then ..

**Comment by grabbou** [comment]
Fixed in master, release pending. Thanks!

**Comment by jukben** [comment]
Master is also broken in this case, see
<img width="373" alt="screen shot 2017-09-11 at 13 38 50" src="https://user-images.githubusercontent.com/8135252/30272827-99584002-96f6-11e7-81d0-28f14e9c150a.png">

**Comment by joearasin** [comment]
Things are broken in master pending https://github.com/facebook/react-native/issues/15791 being fixed.
