### ISSUE TITLE
Doesn't work on iOS < 10

### ISSUE THREAD

**Issue by skevy** [callstack-io/haul#60]
### Current Behavior
On a fresh react-native init/haul init, without changing any settings, and using the iOS 9.2 Simulator, I get the following:
![image](https://cloud.githubusercontent.com/assets/131916/24529465/abfa8106-1560-11e7-89b3-76a8a1f75e0b.png)

### Expected Behavior
I expect that it should work as it does on iOS >= 10.

### Haul Configuration (webpack.haul.js)
It's the default configuration. This is on first run.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.1.2
| react-native     |  0.42.3
| node             | 7.7.4
| yarn      | 0.23.0

**Comment by grabbou** [comment]
I believe it's because of `vendor` code we don't transpile and that on iOS 9, there's a smaller subset of features supported. Testing a fix now.

**Comment by grabbou** [comment]
Released
