### ISSUE TITLE
How does it differ from create-react-native-app

### ISSUE THREAD

**Issue by wilomgfx** [callstack-io/haul#62]
How does this project differs from : https://github.com/react-community/create-react-native-app

Other than using webpack ? (which is cool btw, not saying haul is useless!)
Using webpack and its ecosystem, opens up a whole world of possibilities.

Thanks :)!

**Comment by henrikra** [comment]
I would also like to know benefits of using this. Since the read me did not tell the benefits and I don't want to break my current project :)

**Comment by f0rr0** [comment]
From the readme it looks like `haul` supportts symlinking modules which the normal packager can't

**Comment by henrikra** [comment]
What is the benefit or use case for that?

**Comment by f0rr0** [comment]
@henrikra you often want to develop a module independently along side your app and use it as a dependency from within your app. The usual way is to `npm link` so that `npm` picks up your local dev version. you can't do that in RN since the packager does't support it.

**Comment by satya164** [comment]
Haul is an alternative to the React Native CLI tools which you use to perform actions like bundling JavaScript files for packaging or running a development server.

Haul is based on Webpack, so you have access to the entire Webpack ecosystem and can use any webpack loaders or plugins you need. It also doesn't depend on watchman which is a pain to setup on Windows and have to compile from source on Linux, so hopefully it'll have better cross-platform story. Not using watchman means you can use symlinks, import files outside of your project root etc.

Create React Native App is a framework based on Expo to make development easier. It uses React Native packager internally but that's an implementation detail, and maybe someday we can make it use Haul. But that won't affect your workflow. It solves a completely different purpose.

**Comment by wilomgfx** [comment]
Amazing, Thanks ! Looking forward to use it.

**Comment by lyahdav** [comment]
It would be good to add some from @satya164 comment to the readme. From reading the current readme it wasn't clear to me why I'd want to use Haul.

**Comment by wilomgfx** [comment]
I agree.

**Comment by grabbou** [comment]
Anyone up for sending pull request?
