### ISSUE TITLE
Doesn't work on Node 4.x

### ISSUE THREAD

**Issue by colinramsay** [callstack-io/haul#63]
I tried running `haul` with v4.6.1 of `node` and it failed (`ReferenceError: regeneratorRuntime is not defined`), but with v6 it works. The readme should indicate the minimum required version.

**Comment by grabbou** [comment]
Can you try running #64 to see if it fixes your problem? We support Node 4, but our preset is not including regenerator-runtime. Should be fixed after this PR gets merged and released.

Until then, you can point `haul-cli` to `callstack-io/haul#1afd58644ad576376d481eb6dbf70ea291bf269a` and run install again.

**Comment by colinramsay** [comment]
Oh I just used `nvm` to switch to v6, it wasn't a major issue for me. I just thought it would be useful for the readme to be explicit about it :)

**Comment by grabbou** [comment]
@colinramsay we do support v4, so thanks to your report we were able to locate an issue with our babel preset!

**Comment by colinramsay** [comment]
:man_dancing:

**Comment by grabbou** [comment]
0.1.4 should now work on Node 4
