### ISSUE TITLE
The bundle file size is 6.6M And The sourceMap is 5M

### ISSUE THREAD

**Issue by zimo888** [callstack-io/haul#65]
Hi

I'm running three kinds of command to build bundle file.

1. 
```
haul bundle --platform ios --bundle-output build/index.bundle --assets-dest build/assets  --dev false
```
The file size is 6M.

2.
```
haul bundle --platform ios --bundle-output build/index.bundle --assets-dest build/assets --minify true --dev false
```

The file size is 6.6M.

3.

```
react-native bundle --entry-file index.ios.js --bundle-output ./build/index.rn.bundle --platform ios --dev false 
```
The file size is 576K.

I opened the haul's bundle file ,When I deleted the sourceMap code ,the file size reduced to  1.5M

Could you add any option which can split the sourceMap to another file?

**Comment by grabbou** [comment]
We just pushed a fix with @satya164 that no longer inlines source maps. With next release we are going to ship in a second (waiting for one more PR to land), problem will be gone.
