### ISSUE TITLE
Can't resolve 'react-native' in external react-native component

### ISSUE THREAD

**Issue by QuantumInformation** [callstack-io/haul#73]
I have this project where I am importing a react-native component:

https://github.com/QuantumInformation/react-native-cron/blob/master/demo/index.ios.js#L10

This component tries to import from react-native but it fails:

![image](https://cloud.githubusercontent.com/assets/216566/24560914/8859b55a-163c-11e7-99a6-d810b5cf6dc3.png)

**Comment by satya164** [comment]
Do you have `react-native` installed? Coz I cannot see the dependency in your `package.json`

**Comment by QuantumInformation** [comment]
Yep, I need it in the root project, not just the Demo project thx!
