### ISSUE TITLE
Can't debug at http://localhost:8081/debugger-ui

### ISSUE THREAD

**Issue by QuantumInformation** [callstack-io/haul#75]
I can't access my source files to debug on my project build with haul
![image](https://cloud.githubusercontent.com/assets/216566/24562034/34aad4a2-1641-11e7-985f-7cb8b95cec28.png)

### Haul Configuration (webpack.haul.js)
```js
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});
```
### Your Environment
MAC OSX
| software         | version
| ---------------- | -------
| Haul             |  0.1.3
| react-native     |  0.42.3
| node             | 6.9.1
| npm or yarn      |v0.19.1

![image](https://cloud.githubusercontent.com/assets/216566/24562067/51ec21f6-1641-11e7-8c2d-c5711b5b41ee.png)
![image](https://cloud.githubusercontent.com/assets/216566/24562079/59ab5c86-1641-11e7-9dac-71f7b06c5cb8.png)

**Comment by satya164** [comment]
It says "Status: Waiting", so doesn't look like your phone is connected to the debugger?

**Comment by QuantumInformation** [comment]
I guess so, pressing cmd+R didn't do anything:

![image](https://cloud.githubusercontent.com/assets/216566/24563235/999bebb8-1645-11e7-8502-0a8ca16de338.png)

**Comment by satya164** [comment]
You have to select "Debug with chrome" from the developer menu. I believe it's `Cmd + D`

**Comment by QuantumInformation** [comment]
![image](https://cloud.githubusercontent.com/assets/216566/24563608/ee098f92-1646-11e7-817d-d3957ef34178.png)
Great, that worked:
![image](https://cloud.githubusercontent.com/assets/216566/24563623/0523807a-1647-11e7-8465-fc0c69467c81.png)

**Comment by grabbou** [comment]
Happy coding :)

**Comment by QuantumInformation** [comment]
Note, the menu option has changed to "Debug JS remotely"
