### ISSUE TITLE
Build not being updated, old version showing

### ISSUE THREAD

**Issue by QuantumInformation** [callstack-io/haul#78]
In [this project](https://github.com/QuantumInformation/react-native-cron/tree/master/demo), I tried to stop and start with:

`yarn run haul start -- --platform ios`

But My build still contains the old UI:

![image](https://cloud.githubusercontent.com/assets/216566/24568855/8d9bfea0-165b-11e7-840f-9d8998c49955.png)

After rebuild looks the same:
![image](https://cloud.githubusercontent.com/assets/216566/24569852/22c56bde-1660-11e7-97ee-613a5bd3b86e.png)
 not showing the new code

![image](https://cloud.githubusercontent.com/assets/216566/24569865/30c540c4-1660-11e7-9ec9-00ff91c05a9a.png)

I closed the ios simulator and reran react-native run-ios

**Comment by grabbou** [comment]
Unfortunately, I couldn't reproduce it. 

Try the following:
- Turn on `Live reload` and see if saving reloads your app
- Check if Haul contains any warnings / errors in regards to your application code

From the screenshots, I can see you are using `text`, instead of `Text` (note lowercase), which explains why you are seeing old UI (new one is not compiling)

**Comment by QuantumInformation** [comment]
Changing to Text has no effect I'm afraid:

![image](https://cloud.githubusercontent.com/assets/216566/24855319/219cbf8e-1dd9-11e7-9312-515863e64251.png)

No errors on the haul side. Are you able to see the text now if you compile my app?

**Comment by grabbou** [comment]
Can you provide a full `gist` of your `index.ios.js` so that we can reproduce it? Have you tried running React Native packager to see if it works?

**Comment by QuantumInformation** [comment]
https://github.com/QuantumInformation/react-native-cron/blob/master/demo/index.ios.js

I'm gonna do a fresh install of react native for the 4th time to see if it works, if not I'll have to wait.

**Comment by QuantumInformation** [comment]
no luck

**Comment by satya164** [comment]
This might sound farfetched, but have you checked that you're running the packager in the same folder where you're editing the files? Very easy to make mistake when you've the same folder in 2 places.

**Comment by QuantumInformation** [comment]
I've done a reinstall of everything, somehow its working now.

**Comment by QuantumInformation** [comment]
Sorry guys on this new app, I made a change and then haul saw the change and updated:
![image](https://cloud.githubusercontent.com/assets/216566/24861503/ddf5210a-1df0-11e7-8ae5-0737ea588c18.png)

If I make a change in an external node modules file, then the change is not pulled in, only if I update the actual project code

However running cmd+r and refresh on the debugger UI and the old code is there.

I fired up `yarn run haul start -- --platform ios` again and ran `react-native run-ios` and still the old code in the external node modules folder.

**Comment by QuantumInformation** [comment]
Seems as haul can't recognise any change in node_modules, it only loads the initial version the first time haul is run and then doesn't reload it.
