### ISSUE TITLE
fetch is not a function. (In 'fetch', 'fetch' is undefined)

### ISSUE THREAD

**Issue by fdnhkj** [callstack-io/haul#80]
### Current Behavior
After running an existing RN project with `haul`, I get the error visible in screenshot below
<img width="376" alt="capture d ecran 2017-04-01 a 17 52 02" src="https://cloud.githubusercontent.com/assets/5569608/24580234/e3e459b6-1704-11e7-96ed-3647bc3de4b2.png">

### Expected Behavior
I expected fetch to be accessible in global like when running with `packager`: 
https://github.com/facebook/react-native/blob/master/packager/defaults.js#L41-L44
https://github.com/facebook/react-native/blob/master/Libraries/Core/InitializeCore.js#L176-L186

### Haul Configuration (webpack.haul.js)
The generated haul config:
`module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});`
### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  ^0.1.4
| react-native     |  ^0.42.0
| node             | v7.5.0
| npm or yarn      | 4.1.2

**Comment by satya164** [comment]
Can you try https://github.com/callstack-io/haul/pull/74 and see if it fixes the issue?

**Comment by fdnhkj** [comment]
I just tried #74 via `npm i --save-dev callstack-io/haul#pull/74/head`
And... now it works 👍 

Thanks for the quick reply!
