### ISSUE TITLE
how to exclude my scala.js files ? 

### ISSUE THREAD

**Issue by chandu0101** [callstack-io/haul#83]
with react-native packager  i have a customer Transformer 

https://github.com/scalajs-react-interface/mobile.g8/blob/master/src/main/g8/scalajsTransformer.js

and  `"scripts": { "start": "react-native start server --transformer scalajsTransformer" },` 

how can i achieve something  similar using haul ?

**Comment by satya164** [comment]
Customize the loader you get in `defaults.module.rules` to exclude your file.

https://github.com/callstack-io/haul/blob/master/docs/Configuration.md
https://webpack.js.org/configuration/module/#rule-exclude

**Comment by chandu0101** [comment]
@satya164  thanks for reply 

wepack.haul.js 

```js

var path = require('path')


module.exports = ({ platform },defaults) => ({
  entry: `./index.${platform}.js`,
   module: {
     ...defaults.module,
       rules: [
           ...defaults.module.rules,
                {
                  test: /\.js$/,
                  exclude: [/node_modules\/(?!react|@expo|haul)/,
                  path.resolve(__dirname, 'assets/scalajs-output-ios.js')
                  ],
                  use: {
                    loader: require.resolve('happypack/loader'),
                    query: { id: 'babel' },
                  },
                },

         ],
   }
});
```

index.ios.js 

```js
require("./assets/scalajs-output-ios.js")
```

**Comment by satya164** [comment]
you'll want to filter it our from `defaults.module.rules` too

**Comment by chandu0101** [comment]
>you'll want to filter it out from defaults.module.rules too

i didn't understand this fully,
but my  `scalajs-output-ios.js` is already ES5 , it's redundant to pass it through babel again :s

**Comment by satya164** [comment]
You already have this rule in `defaults.module.rules`, if you don't filter it, then you have two rules for `js`

**Comment by chandu0101** [comment]
oh ok  got you, so i have to filter `defaults.module.rules` before merging right ?

**Comment by chandu0101** [comment]
@satya164  its good to  provide some `option` to provide extra `excludes` and merge them in default `.js` rules  ?

**Comment by grabbou** [comment]
I think in that case instead of merging your rules with default rules, you better providing your own set of rules and forgetting about ours at all. We export an array, so you can take whatever you want by index.

**Comment by satya164** [comment]
I guess better not to rely on index since it'll break when if we add any loaders, but `defaults.module.rules.filter` should be fine

**Comment by chandu0101** [comment]
i think i don't know what i am doing here :( , with this following config , i see build going until 91% 

***webpack.haul.js*** 

```js
var path = require('path')


module.exports = ({ platform },defaults) => ({
  entry: `./index.${platform}.js`,
   module: {
     ...defaults.module,
       rules: [
           ...(defaults.module.rules.filter((obj) => {
           console.log(obj.test);
           obj.test != `/\.js$/` })),
              {
                   test: /\.js$/,
                   exclude: [/node_modules\/(?!react|@expo|haul)/,
                   path.resolve(__dirname, 'assets/scalajs-output-ios.js')],
                   use: {
                     loader: require.resolve('happypack/loader'),
                     query: { id: 'babel' },
                   },
                 },
         ],
   }
});
```

but in the end i am seeing bunch of following errors 

```js
ERROR in ./~/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactRef.js
Module parse failed: project_path/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactRef.js Unexpected token (17:12)
You may need an appropriate loader to handle this file type.
| var ReactOwner = require('ReactOwner');
| 
| import type { ReactInstance } from 'ReactInstanceType';
| import type { ReactElement } from 'ReactElementType';
| 
 @ ./~/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactReconciler.js 14:15-34
 @ ./~/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactUpdates.js
 @ ./~/react-native/Libraries/react-native/react-native-implementation.js
 @ ./assets/scalajs-output-ios.js
 @ ./index.ios.js
 @ multi ./~/haul-cli/src/utils/polyfillEnvironment.js ./index.ios.js

```

**Comment by grabbou** [comment]
On a side note - since this is Webpack - I believe a more efficient way would be to explicitly override `loader` for that particular require rather than adding it to `exclude` list.

Revert back you Haul config to what it used to be in the first commend and replace `require` with the following:
```js
require("!!./assets/scalajs-output-ios.js")
```
The double exclamation mark will disable all preloaders and loaders for that particular call.

**Comment by chandu0101** [comment]
@grabbou  thanks for info , I don't know what added recently,  its working fine now without any hacks.
