### ISSUE TITLE
Clearing console makes it impossible to debug webpack config

### ISSUE THREAD

**Issue by aem** [callstack-io/haul#89]
### Current Behavior
Any `console.log`s in `webpack.haul.js` are cleared immediately

### Expected Behavior
Debugging the webpack config should be possible. At the moment there's no way to check if, say for example, you're extending the default config, the output object is actually what you want it to be. 

Possibly a `--no-clear` option would be helpful, default to the clean console approach but allow override if necessary? I'd be happy to take care of this if you're looking for a PR

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.2.1
| react-native     |  0.42.3
| node             | 7.7.4
| npm or yarn      | yarn 0.21.3

**Comment by satya164** [comment]
It's not cleared. Just moved up. You can scroll up to see old logs

**Comment by aem** [comment]
upon further investigation, it appears that you're correct only if you're using `bash` as your shell. in `zsh` it actually clears the contents

**Comment by grabbou** [comment]
What is the terminal app you are using? I can experience the same behaviour when running `zsh` and `Hyper`. Switching to `iTerm` or `Terminal` works as expected.

**Comment by aem** [comment]
zsh in Terminal.app and zsh in the integrated IntelliJ terminal

**Comment by aem** [comment]
actually, scratch that. i thought i had tested in Terminal, but i guess only in intellij. Looks more like a bug with IntelliJ then. sorry for the noise

**Comment by grabbou** [comment]
It's probably related issue to what `Hyper` is having.
